# Please check the documentation https://autoscout24.atlassian.net/wiki/spaces/DATAPLATFORM/pages/104824833/Product+DataRunner+-+Data+Processing #
domain: <DOMAIN>  # Domain name [required]
team: <TEAM>  # Team name from service catalog [required]
slack_channel: <SLACK_CHANNEL>  # [use airflow-test-alert for dev if you dont have a channel yet] [required]
email: <EMAIL>  # [required]
pipelines:
  - name: my_pipeline # Name of your pipeline [required]
    description: <DESCRIPTION> # Description of your pipeline [required]
    business_owner: <BUSINESS_OWNER> # Data Product Owner [required]
    technical_owner: <TECHNICAL_OWNER>  # The developer or the team implementing the pipeline [required]
    schedule_interval: <CRON> # cron [required] [example: 00 10 * * *]
    tasks:
      - name: <NAME>  # Name of the task [required]
        description: <DESCRIPTION>  # Description of the task [required]
        util: DataProduct  # [required]
        actions:  # [required]
          - name: <NAME>  # Name of the action [required]
            util: CreateTable  # [required]
            module: from_query  # [required]
            size: medium  # [if not provided default value is medium] [options: small|medium|large|extra_large] [optional]
            args:  # [required]
              s3_file_path: <S3_FILE_PATH>  # [required]
              database: <DATABASE>  # [required]
              table: <TABLE>  # [required]
              partition_columns: <COLUMN> <DATA_TYPE>  # [optional, can be commented or removed]
              sql_file_path: <PATH_TO_SQL_IN_REPO>  # [example: src/project_2/my_sql.sql] [required]
